project:
  type: website
  output-dir: _site
  resources: 
    - "*.csv"
    - "webr-serviceworker.js"
    - "webr-worker.js"


website:
  title: "Portal Project - Tidy Tuesday"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: Getting Started
      - href: base.qmd
        text: Base R
      - href: tidyverse.qmd
        text: Tidyverse

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
