project:
  type: website
  output-dir: _site
  resources: 
    - "*.csv"
    - "webr-serviceworker.js"
    - "webr-worker.js"


website:
  title: "Portal Project - Tidy Tuesday"

format:
  html:
    theme: flatly
    toc: true
