---
title: Getting started with webR for Tidy Tuesday
editor: visual
engine: knitr
filters:
  - webr
---

## Load the data

WebR only has limited packages, so we'll load the data directly.
Click `Run code` to load the data.

```{webr-r}
surveys <- read.csv("https://tidytuesday.weecology.org/surveys.csv")
species <- read.csv("https://tidytuesday.weecology.org/species.csv")
plots <- read.csv("https://tidytuesday.weecology.org/plots.csv")
```

Take a look at the data here (e.g., `head(surveys)`).
Any commands you enter will be run when you click `Run code`.

```{webr-r}
```


::: {.callout-warning}

## Not all NA's are NA's

There is a species code `"NA"` for [_Neotoma albigula_](https://en.wikipedia.org/wiki/White-throated_woodrat).
Try adding `na.strings = ""` to `read.csv()` for `surveys` and `species` to properly import it.
You can change them right in the code block and click `Run code` to rerun.

:::

## Install packages

To install packages in `webr` use `webr::install()` with a vector of packages you want to install.

The following packages are currently available in `webr`:

```{r, echo=FALSE}
#| class: scrolling
packages = read.csv("https://raw.githubusercontent.com/r-wasm/webr-repo/main/repo-packages")
packages$Formula
```
<br>
Install any packages you want here by changing `package1` with the package name you want to install:

```{webr-r}
webr::install(c('package1'))
```

::: {.callout-warning}
# Big packages can be a little slow

Big packages like `ggplot2` can be a little slow to install and load in WebR

:::

## Tidy Tuesday away!

Anything you type in this block will run when you click `Run code`.
This cell also has access to objects created in other WebR cells on this page (like the data and packages installed above).
Enjoy!

```{webr-r}
```