---
editor: visual
engine: knitr
filters:
  - webr
---

## WebR

[WebR](https://docs.r-wasm.org/webr/latest/) is a version of R that runs in the browswer.
You don't need to install R and no one needs to setup a server, it just runs on your local computer, but through your browser.
This site lets you use it for this weeks Tidy Tuesday using the long-term monitoring data on mammals from [the Portal Project](https://portal.weecology.org). 

## Data

## Let's go!

There are three pages on this site:

1. [Getting Started](/getting-started.qmd) - will walk you through loading the data and installing packages in WebR
2. [Base R](/base.qmd) - gives you a Base R only setup with the data already loaded
3. [Tidyverse](/tidyverse.qmd) - gives you R + dplyr + ggplot2 and the data already loaded. _This page takes about 20 seconds to load the packages_

## What is this magic

If you want to see how all of this works you can checkout the [GitHub repository](https://github.com/weecology/tidy-tuesday-portal) for this site.
The site uses [Quarto](https://quarto.org/) with the [Quarto WebR extension](https://github.com/coatless/quarto-webr).  
Preloading data on the [Base](/base.qmd) and [Tidyverse](/tidyverse.qmd) pages requires a little bit of javascript.